name: "scan2html"
repository: github.com/fatihtokus/scan2html
version: "0.2.2"
usage: scan targets into a smart html file
description: |-
  A Trivy plugin that scans and outputs the results to a html file.
  trivy scan2html [-h,--help] command target filename
platforms:
  - selector:
      os: windows
    uri: https://github.com/fatihtokus/scan2html/releases/download/v0.2.2/scan2html.tar.gz
    bin: ./scan2html.sh
  -
    uri: https://github.com/fatihtokus/scan2html/releases/download/v0.2.2/scan2html.tar.gz
    bin: ./scan2htmlPlugin
