#!/bin/bash

# help
function help() {
  cat << EOS >&2
scan2html v0.0.1

Usage: trivy scan2html [-h,--help] command target filename
 A Trivy plugin that scans and output the results to a html file.
Options:
  -h, --help    Show usage.
Examples:
  # Scan `alpine:latest` image
  trivy scan2html image alpine:latest result.html

  # Scan local folder
  trivy scan2html fs . result.html
EOS
  exit
}


tmp_result="result.json"

function scan {
  BASEDIR=$(dirname "$0")
  args=("${@:2:$#-2}")
  last_arg="${!#}"
  scanner="$1"
  set -- "$1" "${args[@]}" "$last_arg"
  echo "$BASEDIR"
  echo "$args"
  echo "$last_arg"
  trivy "$scanner" --format json -o "$BASEDIR"/$tmp_result "${args[@]}"
  cat "$BASEDIR"/report_template.html >>$last_arg
  {
    echo "<script>"
    echo "const resultJson = "
    cat  "$BASEDIR"/$tmp_result
    echo "</script>"
    echo "<script>"
    echo "const scanner = '$scanner';"
    echo "const createdAt = $(date +%s);"
    echo "init();"
    echo "</script>"
    echo "</body>"
    echo "</html>"
  } >>$last_arg

  trap 'rm -f $tmp_result' EXIT
}

if [[ ($# -eq 0) || ($1 == "--help") || ($1 == "-h") ]]; then
  help
fi

scan "$@"