name: Release go

on:
  workflow_call:
    inputs:
      next-version:
        required: true
        description: Next version
        type: string

jobs:
  release-go:
    name: Release go
    runs-on: ubuntu-latest
    if: ${{ inputs.next-version != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Tagging
        run: git tag v${{ inputs.next-version }}

      - name: Determine if Pre-Release
        id: prerelease-check
        run: |
          if [[ "${{ inputs.next-version }}" == *"rc"* ]]; then
            echo "PRERELEASE=--prerelease" >> $GITHUB_ENV
          else
            echo "PRERELEASE=" >> $GITHUB_ENV
          fi

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          # this doesn't work
          prerelease: '{{ .Tag | regexMatch `-rc\.` }}'
          args: release --clean --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v${{ inputs.next-version }}