name: Release go

on:
  workflow_call:
    inputs:
      next-version:
        required: true
        description: Next version
        type: string

#permissions:
#  contents: read

permissions:
  contents: read

jobs:
  release-go:
#    permissions:
#      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    name: Release go
    runs-on: ubuntu-latest
    if: ${{ inputs.next-version != '' }}
    steps:
#      - name: Harden Runner
#        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
#        with:
#          egress-policy: audit

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout code
#        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Download report_template.html
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
#        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: report-template

      - name: Use the downloaded report template
        run: |
          ls -l report_template.html
          cat report_template.html

      - name: Set up Go
#        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod

      - name: Tagging
        run: git tag v${{ inputs.next-version }}

      - name: Cosign install
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4

      - name: "save gpg key"
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_KEY" > gpg.key

      - name: GoReleaser
#        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: latest
          # this doesn't work
          #prerelease: '{{ .Tag | regexMatch `-rc\.` }}'
          args: release --clean --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v${{ inputs.next-version }}
          GPG_FILE: "gpg.key"

      - name: "remove gpg key"
        run: |
          rm gpg.key