name: Release

on:
  push:
    branches:
      - SH-21

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      reportTemplate: 'report_template.html'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: SH-21

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          working-directory: src/frontend-app

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: src/frontend-app

      - name: Build project
        run: |
          pwd
          cd src/frontend-app/
          npm run build

      - name: Preparing report_template.html
        run: |
          # copy js files
          cat
          {
          # copy report file except the last 4 lines
          head -n -4 'src/frontend-app/dist/src/assets/app-template.html'
          echo ''
          cat 'src/frontend-app/dist/app.js'
          echo ''
          echo '</script>'
          echo '</body>'
          echo '</html>'
          } >"$reportTemplate"
          
          cat "$reportTemplate"
      - name: Compress
        run: tar -zcvf scan2html.tar.gz scan2html "$reportTemplate" LICENSE results.json

      - name: Archive plugin
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: scan2html.tar.gz
